### ISSUE TITLE
Get more than one day of EPG

### ISSUE THREAD

**Issue by thlayli123** [deathbybandaid/locastepg#2]
Can the script download more than one day's worth of EPG? I noticed on the locast site, they have about a week's worth of EPG data.

**Comment by deathbybandaid** [comment]
That's something I will look into. The API is highly undocumented, and it seems to be split into 24 hours.

**Comment by thlayli123** [comment]
yeah, I saw that too. I did notice when looking at the http requests that the actual request on their web page looks like this: https://api.locastnet.org/api/watch/epg/807?startTime=2020-09-11T00%3A00%3A00-05%3A00
This translates to 2020-09-11T00:00:00-05:00
I have done some experimenting, and the -05:00 is actually the time offset from utc, as I mentioned in my other issue. 
I'm a beginner when it comes to development, but I thought maybe pulling 7 urls (1 each for say 7 days), and joining their json results before manipulating them into the xml might work.

**Comment by deathbybandaid** [comment]
I wasn't aware of what the URL arguments were

**Comment by deathbybandaid** [comment]
I finally have time to check on doing this today.

**Comment by deathbybandaid** [comment]
I now have 7 days of EPG imported with caching

**Comment by thlayli123** [comment]
Awesome! This is great!
